#!/bin/bash

[ -n "$DOSSH_CMD" ] || { echo "Undefined variable: DOSSH_CMD"; exit 1; }
[ -n "$IP_OFFSET" ] || { echo "Undefined variable: IP_OFFSET"; exit 1; }
[ -n "$1" ] || { echo "Parameter missing: IP1"; exit 1; }
[ -n "$2" ] || { echo "Parameter missing: IP2"; exit 1; }

IP1=$1
shift
IP2=$1
shift

for I in `seq $IP1 $IP2`
do
  IP=`expr $I + $IP_OFFSET`
  echo -e '\E[33;31m'"\033[1m  ===== 172.16.3.$IP ======\033[0m"
  $DOSSH_CMD.$IP "$*"
done
