#!/bin/bash

SEQ_SPLITTERS="1 2 4 6"
SEQ_MAPPERS="1 2 4 6"
SEQ_REDUCERS="1 2 4 6"
SEQ_WORKERS="1 2 4 6"
NUMOFTESTS="1"
RUNTEST2="/home/re/holumbus/mapreduce/Examples2/MandelWithSimpleIO/runtest2"
FILENAME="test.pgm"
OPTS="(1280,1024,2.0,100)"

for Y in `seq 1 $NUMOFTESTS`
do

  # make a dir for current run
  mkdir "run_$Y"

  # change into testdir
  cd "run_$Y"

  for SPLITTERS in $SEQ_SPLITTERS
	do
    for MAPPERS in $SEQ_MAPPERS
		do
      for REDUCERS in $SEQ_REDUCERS
      do
  			# start the actual tests
			  for WORKERS in $SEQ_WORKERS
			  do
        $RUNTEST2 $WORKERS $SPLITTERS $MAPPERS $REDUCERS "$FILENAME" "$OPTS"
				done
		  done
		done
	done
  
  # change to root dir
  cd ..

done
