#!/bin/bash

NUM="20"
SEQ_SPLITTERS="$NUM"
SEQ_MAPPERS="$NUM"
SEQ_REDUCERS="$NUM"
SEQ_WORKERS="$NUM"
NUMOFTESTS="1"
RUNTEST2="/home/re/crawl2/Examples2/Re/runtest2"

echo unconfigrued
exit 1

for Y in `seq 1 $NUMOFTESTS`
do

  # make a dir for current run
  mkdir "run_$Y"

  # change into testdir
  cd "run_$Y"

  for SPLITTERS in $SEQ_SPLITTERS
	do
    for MAPPERS in $SEQ_MAPPERS
		do
      for REDUCERS in $SEQ_REDUCERS
      do
  			# start the actual tests
			  for WORKERS in $SEQ_WORKERS
			  do
        $RUNTEST2 $WORKERS $SPLITTERS $MAPPERS $REDUCERS
				done
		  done
		done
	done
  
  # change to root dir
  cd ..

done
