#!/bin/bash

BASE="/home/re/FH/holumbus"

function mydirname () {
  echo $2 | sed "s|$1||g"
}

DEBUG="#"

for I in mapreduce distribution storage
do
  BASE2="$BASE/$I/source/"
  SRC_FILES=`find "$BASE2" -name "*.hs"`
  for SRC_FILE in $SRC_FILES
  do
    SRC_FILE_BASE=`basename "$SRC_FILE"`
    DEST_FILE="$(mydirname "$BASE2" "$SRC_FILE")"
    # ">>> SRC: $SRC_FILE"
    # ">>> DST: $DEST_FILE"
    [ $DEST_FILE -ot $SRC_FILE ] && { echo "Copy $SRC_FILE to $DEST_FILE"; cp $SRC_FILE $DEST_FILE; }
  done
done
