#!/bin/bash

DEBUG=0

NUM=1
[ -n "$1" ] && NUM=$1

BASE="."
[ -n "$2" ] && BASE=$2

WORKER="/home/re/MyExamples/Mandel/MandelWorker"
[ -n "$3" ] && WORKER=$3
[ -f "$WORKER" ] || { echo "No such file: $WORKER"; exit 1; }

if [ $DEBUG -eq 1 ]
then
	echo "Num : $NUM"
  echo "Base: $BASE"
fi

#mkdir $BASE/worker
while [ $NUM -ne 0 ]
do
	echo "init worker $NUM"
  mkdir "$BASE/worker$NUM"
  cp $WORKER $BASE/worker$NUM/
  NUM=`expr $NUM - 1`
done
