#!/bin/bash

CLIENT="/home/re/holumbus/mapreduce/Examples2/MandelWithoutReduce_snd/Client"
STARTWORKER_BIN="startworkermandel MandelWithoutReduce_snd"
STOPWORKER_BIN="stopworkermandel"
WORKERS="$1"
SPLITTERS="$2"
MAPPERS="$3"
REDUCERS="$4"
FILENAME="$5"
OPTS="$6"

echo "Doing run: $WORKERS / $SPLITTERS / $MAPPERS / $REDUCERS"
# Start MR sytem and wait a sec
/etc/init.d/MR start && sleep 1

# Start I workers
$STARTWORKER_BIN 1 $WORKERS

# Wait for workers to be started
while [ `cat /tmp/master.state|wc -l` -ne $WORKERS ]; do echo "Waiting for workers to be started" && sleep 1; done

sleep 2

# make a new dir for curretn constelation
FILENAME_PREFIX="$WORKERS""_""$SPLITTERS""_""$MAPPERS""_""$REDUCERS"
mkdir "data_$FILENAME_PREFIX" || { echo "dir exist do not overwrite it: exit"; $STOPWORKER_BIN 1 $WORKERS; /etc/init.d/MR stop; exit 1; }
cd "data_$FILENAME_PREFIX"

# run function
/usr/bin/time -o "time.txt" -v "$CLIENT" "$FILENAME" "$OPTS" "($SPLITTERS,$MAPPERS,$REDUCERS)" +RTS -N3 -K4G -s"Memory.txt"

# stop workers
$STOPWORKER_BIN 1 $WORKERS

# copy workers memory data to here
sleep 2
mkdir workerdata
cd workerdata
for I in `seq 1 $WORKERS`
do
  [ $I -eq 25 ] && continue
  [ $I -eq 24 ] && continue
  [ $I -eq 23 ] && continue
  [ $I -eq 15 ] && I=24
  [ $I -eq 19 ] && I=23

  mkdir "worker_$I"
  cd "worker_$I"
  scp root@172.16.3.$I:/tmp/worker/*.txt . > /dev/null
  cd ..
done

# leave curren tdir
cd ..

# stop mr system and wait a sec
/etc/init.d/MR stop && sleep 1
