#!/bin/bash

[ -n "$DOSSH" ] || { echo "$0 Undefined variable: DOSSH"; exit 1; }
[ -n "$WORKER_DIR" ] || { echo "$0 Undefined variable: WORKER_DIR"; exit 1; }
[ -n "$WORKER_SSH_LOCATION" ] || { echo "$0 Undefined variable: WORKER_SSH_LOCATION"; exit 1; }
[ -n "$WORKER_BIN" ] || { echo "$0 Undefined variable: WORKER_BIN"; exit 1; }
[ -n "$WORKER_SH" ] || { echo "$0 Undefined variable: WORKER_SH"; exit 1; }
[ -n "$WORKER_PID" ] || { echo "$0 Undefined variable: WORKER_PID"; exit 1; }
[ -n "$1" ] || { echo "$0 Parameter missing: OPT"; exit 1; }
[ -n "$2" ] || { echo "$0 Parameter missing: IP1"; exit 1; }
[ -n "$3" ] || { echo "$0 Parameter missing: IP2"; exit 1; }

OPT="$1"
shift

case $OPT in
  start)
  $DOSSH $1 $2 "rm $WORKER_DIR -rf && mkdir -p $WORKER_DIR && cd $WORKER_DIR && scp $WORKER_SSH_LOCATION/$WORKER_BIN .  &&  scp $WORKER_SSH_LOCATION/scripts/$WORKER_SH . && start-stop-daemon --start -p $WORKER_DIR/$WORKER_PID --background --startas $WORKER_DIR/$WORKER_SH $WORKER_DIR 10000 $WORKER_PID"
  ;;
  stop)
  $DOSSH $1 $2 "start-stop-daemon --stop --signal 2 -p $WORKER_DIR/$WORKER_PID"
  ;; 
esac
