#!/bin/bash

[ -n "$MR_BIN" ] || { echo "Undefined variable: MR_BIN"; exit 1; }
[ -n "$COPY_REGISTRY_COMMAND" ] || { echo "Undefined variable: COPY_REGISTRY_COMMAND"; exit 1; }
[ -n "$1" ] || { echo "Parameter missing: IP1"; exit 1; }
[ -n "$2" ] || { echo "Parameter missing: IP2"; exit 1; }

IP1="$1"
IP2="$2"

$MR_BIN start

for I in `seq $IP1 $IP2`
do
  [ $I -eq 6 ] && I=21
  [ $I -eq 16 ] && I=24
  echo "Copy registry data to: 172.16.3.$I"
  $COPY_REGISTRY_COMMAND.$I:/tmp/
done

$MR_BIN stop
