#!/bin/bash

FILENAME="$1"
I="$2"
WORDS="$3"

make clean && make

# Start MR sytem and wait a sec
/etc/init.d/MR start && sleep 1

# Start I workers
startworkercount2 1 $I

# Wait for workers to be started
while [ `cat /tmp/master.state|wc -l` -ne $I ]; do echo "Waiting for workers to be started" && sleep 1; done

cp Client client/
cd client/
rm storage/* -f

echo -n "Press Enter to start .."
read
# run sum function
time ./Client "$FILENAME" $I "$WORDS"  +RTS -N3 -K4G -RTS

# stop workers
killworker 1 $I

# stop mr system and wait a sec
/etc/init.d/MR stop && sleep 1
