#!/bin/bash

NUM="1 5 10 15 20 25"
NUMOFTESTS="$1"
CLIENT="/home/re/holumbus/mapreduce/Examples2/CountWithSimpleIO/client/Client"

for Y in `seq 1 $NUMOFTESTS`
do

  # make a dir for current run
  mkdir "run_$Y"

  # change into testdir
  cd "run_$Y"

  for SPLITTERS in $NUM
	do
    for MAPPERS in $NUM
		do
      for REDUCERS in $NUM
      do
  			# start the actual tests
			  for WORKERS in $NUM
			  do
    			# Start MR sytem and wait a sec
		  	  /etc/init.d/MR start && sleep 1

    			# Start I workers
			    startworkercount2 1 $WORKERS

  	  		# Wait for workers to be started
			    while [ `cat /tmp/master.state|wc -l` -ne $WORKERS ]; do echo "Waiting for workers to be started" && sleep 1; done

    			# delete clients storage folder
		    	rm storage/*
  
	    		# run sum function
          FILENAME_PREFIX="$WORKERS_$SPLITTERS_$MAPPERS_$REDUCERS.txt"
			    /usr/bin/time -o "time_$FILENAME_PREFIX" -v "$CLIENT" "/root/Count/nt" "($SPLITTERS,$MAPPERS,$REDUCERS)" "God" +RTS -N3 -K4G -o"Memory_$FILENAME_PREFIX"-RTS

    			# stop workers
		  	  killworker 1 $WORKERS
  
    			# stop mr system and wait a sec
			    /etc/init.d/MR stop && sleep 1
				done
		  done
		done
	done
  
  # change to root dir
  cd ..

done
