#!/bin/bash

CLIENT="/home/re/holumbus/mapreduce/Examples2/CountWithSimpleIO/Client"
WORKERS="$1"
SPLITTERS="$2"
MAPPERS="$3"
REDUCERS="$4"
FILENAME="$5"
WORDS="$6"

echo "Doing run: $WORKERS / $SPLITTERS / $MAPPERS / $REDUCERS"
# Start MR sytem and wait a sec
/etc/init.d/MR start && sleep 1

# Start I workers
startworkercount2 1 $WORKERS

# Wait for workers to be started
while [ `cat /tmp/master.state|wc -l` -ne $WORKERS ]; do echo "Waiting for workers to be started" && sleep 1; done

sleep 2

# make a new dir for curretn constelation
FILENAME_PREFIX="$WORKERS""_""$SPLITTERS""_""$MAPPERS""_""$REDUCERS"
mkdir "data_$FILENAME_PREFIX" || { echo "dir exist do not overwrite it: exit"; exit 1; }
cd "data_$FILENAME_PREFIX"

# run function
/usr/bin/time -o "time.txt" -v "$CLIENT" "$FILENAME" "($SPLITTERS,$MAPPERS,$REDUCERS)" "$WORDS" +RTS -N3 -K4G -s"Memory.txt"

# stop workers
stopworkercount2 1 $WORKERS

# copy workers memory data to here
sleep 2
mkdir workerdata
cd workerdata
for I in `seq 1 $WORKERS`
do
  mkdir "worker_$I"
  cd "worker_$I"
  scp root@172.16.3.$I:/tmp/worker/Memory* . > /dev/null
  cd ..
done

# leave curren tdir
cd ..

# stop mr system and wait a sec
/etc/init.d/MR stop && sleep 1
